### ISSUE TITLE
Could not pass event

### ISSUE THREAD

**Issue by nirewen** [Brokkonaut/Bukkit-CreativeItemControl#1]
I've been using CIC without touching the configuration for a while, but I noticed some items I didn't want to be blocked were so I started adding them in the config.yml. It worked, but now for some reason this error is happening:
`Could not pass event InventoryCreativeEvent to CreativeItemControl v1.13.1.3-SNAPSHOT-brokko`
Full error: https://pastebin.com/MTWT8XtL

It wasn't happening before, and it always work for a while even with another version. 

I don't know for sure what is the cause, but the error says about `checkBlacklist`

**Comment by Brokkonaut** [comment]
Looks like you removed the blacklisted part from your config.

https://github.com/Brokkonaut/Bukkit-CreativeItemControl/blob/master/src/resources/config.yml#L99-L100
