### ISSUE TITLE
dependency libnbt not found

### ISSUE THREAD

**Issue by seema84** [Brokkonaut/Bukkit-CreativeItemControl#7]
http://cyberiantiger.org/ does not seem to be available

**Comment by Brokkonaut** [comment]
If you want to build CreativeItemControl, you should build this dependency first: https://github.com/Brokkonaut/Bukkit-LibNBT

If you just want to download the compiled plugin: https://www.iani.de/jenkins/job/Bukkit-CreativeItemControl/

**Comment by seema84** [comment]
I just wanted to bring it to your attention but thank you
