### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by seema84** [Brokkonaut/Bukkit-CreativeItemControl#9]
It's quite hard to describe, but when you swap different armour that has a smithing template in your inventory, it gets blocked and items disappear or lose their smithing template.

The following error is displayed:
player attempted to spawn in {"id" : "minecraft:netherite_chestplate", "tag" : {"Trim" : {"material" : "minecraft:redstone", "pattern" : "minecraft:silence"}}, "Count" : 1b}

**Comment by Brokkonaut** [comment]
I tried to reproduce this, but was not able to do so. I tried with Right clicking armor parts in the closed inventory and with clicking to pickup the item and put it in the slot, but no errors. What exactly did you click to get this error?

**Comment by seema84** [comment]
It's not easy to describe, I'll make a video for you.

**Comment by seema84** [comment]
https://github.com/Brokkonaut/Bukkit-CreativeItemControl/assets/2832339/b2d52617-1b33-423e-8132-ce8129affd2b

It is important not to put the item down and to leave the inventory by pressing Esc (and sometimes wait a little). As you can see, the item/NBT data will then also change (sometimes it even disappears).

**Comment by Brokkonaut** [comment]
Ok thank you for the detailed report. Can you please try the latest build, it should be fixed now.

**Comment by seema84** [comment]
Build #87 seems to have fixed the problem.
